sudo: false

language: c

env:
- PATH=~/racket/bin:$PATH

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- curl -L -o installer.sh http://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-precise.sh
- sh installer.sh --in-place --dest ~/racket/

install:
- raco pkg install --auto git://github.com/pnwamk/ddict.git
- git clone https://github.com/pnwamk/ddict.git ~/ddict

script:
- raco test ~/ddict/tests/data/ddict.rkt
- echo "done"

after_script:
